### ISSUE TITLE
Couldn't find file "sysmbols/usde" in include paths

### ISSUE THREAD

**Issue by ZulluBalti** [inlart/dotfiles#1]
Hi,

I've copied your dotfiles using git clone and then running the script.
Sway is running correctly and everything seems to be working fine However I this error that says

"Error on line 18 (path to the  config file) 'xkb_layout usde': Failed to compile keymap: Couldn't find file "sysmbols/usde" in include paths

Am I missing any package?

**Comment by inlart** [comment]
Hi,
thank you for reporting this issue. I was loading a custom keyboard layout which is only available on my system. I removed that part from the sway config now. Once you update to the latest version you should no longer get this error.

**Comment by ZulluBalti** [comment]
thank you for solving it in such short amount of time
